[project]
name = "nekt-tap-jira-nekt"
version = "0.0.1"
description = "`tap-jira` is a Singer tap for tap-jira, built with the Meltano Singer SDK."
readme = "README.md"
authors = [{ name = "Ethan Stein" }]
license = "Apache-2.0"
keywords = [
    "ELT",
    "tap-jira-nekt",
]
requires-python = ">=3.11"
dependencies = [
    "fs-s3fs>=1.1.1",
    "inflection>=0.5.1",
    "nekt-singer-sdk @ git+https://github.com/nektcom/singer-sdk.git@v0.23.0",
    "requests~=2.32.2",
]

[project.optional-dependencies]
s3 = [
    "fs-s3fs",
]

[project.scripts]
tap-jira-nekt = 'tap_jira_nekt.tap:TapJira.cli'

[dependency-groups]
dev = [
    "pytest>=8",
]

[tool.hatch.build.targets.wheel]
packages = [
    "tap_jira_nekt",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
python_version = "3.9"
warn_unused_configs = true

[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
select = ["ALL"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.isort]
known-first-party = ["tap_jira_nekt"]

[tool.ruff.lint.pydocstyle]
convention = "google"


[build-system]
requires = ["hatchling>=1,<2"]
build-backend = "hatchling.build"
